name: vSkeleton

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vskeleton-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage
      - name: Prepare Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Download Database
        uses: wei/wget@v1.1.1
        with:
          args: -O database.sqlite -P database https://tests.cryental.dev/volistx/minako/database.sqlite
      - name: Prepare Cache Data
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: |
          php artisan scout:import "App\Models\MALAnime"
          php artisan scout:import "App\Models\NotifyAnime"
          php artisan scout:import "App\Models\NotifyCharacter"
          php artisan scout:import "App\Models\NotifyCharacterRelation"
          php artisan scout:import "App\Models\NotifyCompany"
          php artisan scout:import "App\Models\NotifyRelation"
          php artisan scout:import "App\Models\OhysRelation"
          php artisan scout:import "App\Models\OhysTorrent"
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
